###testing ost user
POST http://localhost:8000/api/v1/user/register
Content-Type: application/json

{
    "name": "admin",
    "email": "ad@ad.com",
    "password": "1"
}

###get
get http://localhost:8000/api/v1/user/665e58dfc2bd290f0275b5f1


###login
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "1"
}


###post product
POST http://localhost:8000/api/v1/product
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjYwMzNlZmRiZGYyNWNjZjNmYjU2YzMiLCJpYXQiOjE3MTc1OTU4MjQsImV4cCI6MTcxNzU5OTQyNH0.DbPxvHo_AeKWJwbm2NgslnkJt53KC39IMGAJicUY5Bc

{
    "name": "Product 13",
    "price": 100,
    "description": "This is the description for product 6.",
    "images": [
      "https://unsplash.com/photos/a-squirrel-eating-a-nut-in-a-field-of-daisies-igYIeewfnOs",
      "https://unsplash.com/photos/a-squirrel-eating-a-nut-in-a-field-of-daisies-igYIeewfnOs"
    ],
    "category": "6660599f5fa21f0dd54d3a09" 
}


###get products
get http://localhost:8000/api/v1/product


###get products by id
get http://localhost:8000/api/v1/product/6660382b379d83338e97cd70


###post category
post http://localhost:8000/api/v1/category
Content-Type: application/json

    {
    "name": "Electronics",
    "description": "Devices and gadgets including phones, laptops, and accessories.",
    "createdAt": "2023-01-01T00:00:00.000Z",
    "updatedAt": "2023-01-01T00:00:00.000Z"
  }


###get all category
get http://localhost:8000/api/v1/category

### POST request to add an item to the cart
POST http://localhost:8000/api/v1/cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjYwMzNlZmRiZGYyNWNjZjNmYjU2YzMiLCJpYXQiOjE3MTkzOTUwMTgsImV4cCI6MTcxOTM5ODYxOH0.1JkQMGTMDfWzO1Z1QpHfsEzqt553_qBlzDokeZOfsp0

{
    "productId": "66603823379d83338e97cd6e",
    "quantity": 2
}

### PUT request to update a cart item
PUT http://localhost:8000/api/v1/cart/your_cart_item_id_here
Content-Type: application/json

{
    "quantity": 3
}

### DELETE request to remove a cart item
DELETE http://localhost:8000/api/v1/cart/your_cart_item_id_here

### GET request to fetch all items in the cart
GET http://localhost:8000/api/v1/cart


###testing the payment
POST http://localhost:8000/api/v1/checkout/create-session
Content-Type: application/json

{
  "cart": {
    "items": [
      {
        "product": {
          "name": "Sample Product 1",
          "description": "Description of Sample Product 1",
          "price": 10
        },
        "quantity": 2
      },
      {
        "product": {
          "name": "Sample Product 2",
          "description": "Description of Sample Product 2",
          "price": 15
        },
        "quantity": 1
      }
    ]
  }
}


### POST New Order ###
POST http://localhost:8000/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjYwMzNlZmRiZGYyNWNjZjNmYjU2YzMiLCJpYXQiOjE3MTk2MjA2NzAsImV4cCI6MTcxOTYyNDI3MH0.wF0eMbFItmmqk4COZEkQozyI2PFbNO7tb7pgMkHhAbw

{
  "user": "666033efdbdf25ccf3fb56c3",
  "products": [
    {
      "product": "6660382b379d83338e97cd70"
    }
  ]
}


### POST New Order ###
Get http://localhost:8000/api/v1/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjYwMzNlZmRiZGYyNWNjZjNmYjU2YzMiLCJpYXQiOjE3MTk2MjA2NzAsImV4cCI6MTcxOTYyNDI3MH0.wF0eMbFItmmqk4COZEkQozyI2PFbNO7tb7pgMkHhAbw