###testing ost user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "password": "secretpassword"
}

###get
get http://localhost:8000/api/v1/user/665e58dfc2bd290f0275b5f1


###login
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "secretpassword"
}